import { defineMessages, type Locale } from './i18n.ts';
import { LIMITS } from './limits.ts';

export const ERRORS = defineMessages({
  'zh-CN': {
    invalidParams: '参数错误',
    internalError: '服务器开小差了，请稍后再试',
    apiNotFound: '接口不存在',
    crossSiteRejected: '跨站请求被拒绝',
    unknownMethod: ({ method }: { method: string }) => `未知方法 ${method}`,
    tooManyAttempts: '尝试过于频繁，请稍后再试',
    unauthorized: '未登录或登录已过期',
    adminSessionInvalid: '管理员登录已失效，请重新登录',
    adminSessionExpired: '管理员登录已过期，请重新登录',
    passwordLoginDisabled: '当前未启用密码登录',
    wrongPassword: '密码错误',
    sharedModeNoPassphrase: '共享模式无需口令',
    ledgerSessionExpired: '当前浏览器的账本登录已过期，请输入口令',
    passphraseRequired: '请输入账本口令',
    passphraseInvalid: '口令无效或已过期',
    passphraseNotYetValid: '口令尚未生效',
    passphraseInUse: '该口令正在使用中，请换一个',
    passphraseNotFound: '口令不存在',
    ledgerNotFound: '账本不存在',
    ledgerExists: ({ name }: { name: string }) => `账本「${name}」已存在`,
    memberNotFound: '成员不存在',
    memberExists: ({ name }: { name: string }) => `成员「${name}」已存在`,
    memberLimit: `成员最多 ${LIMITS.members} 位`,
    memberInUse: '该成员已有相关账目，无法删除',
    payerNotFound: '付款人不存在',
    participantNotFound: '参与者不存在',
    expenseNotFound: '这笔支出不存在或已被删除',
    settlementNotFound: '这笔还款不存在或已被删除',
    connectionNotFound: '该连接不存在或已断开',
    assistantDisabled: '未启用 AI 助手',
    assistantRateLimited: 'AI 助手太忙了，请稍后再试',
    assistantUnavailable: 'AI 助手暂时不可用，请稍后再试',
    assistantFailed: 'AI 助手出错了，请重试',
    mcpDisabled: 'MCP 未启用',
    oauthMissingClientId: '授权请求缺少 client_id',
    oauthUnknownClient: '未知的客户端，请在 AI 应用中重新添加连接',
    oauthRedirectMismatch: '回调地址与客户端注册的不一致',
    oauthScopeRequired: '至少需要查看权限',
    titleRequired: '用途不能为空',
    titleTooLong: `用途最多 ${LIMITS.title} 个字`,
    memberNameRequired: '名字不能为空',
    memberNameTooLong: `名字最多 ${LIMITS.memberName} 个字`,
    ledgerNameRequired: '账本名称不能为空',
    ledgerNameTooLong: `账本名称最多 ${LIMITS.ledgerName} 个字`,
    dateFormat: '日期格式应为 YYYY-MM-DD',
    dateInvalid: '日期无效',
    amountNotCents: '金额需以分为单位',
    amountNotPositive: '金额必须大于 0',
    amountTooLarge: '金额过大',
    codeTooShort: `口令至少 ${LIMITS.codeMin} 位`,
    codeTooLong: `口令最多 ${LIMITS.codeMax} 位`,
    codeCharset: '口令只能包含字母和数字',
    participantsRequired: '至少选择一位参与者',
    participantsDuplicate: '参与者重复',
    participantsTooMany: `参与者最多 ${LIMITS.members} 位`,
    shareNotPositive: '每人金额至少 0.01 元',
    sharesDuplicate: '分摊成员重复',
    sharesSumMismatch: '各人金额之和需等于总额',
    categoryInvalid: '分类无效',
    idInvalid: '记录 ID 无效',
    idExists: '这条记录已存在',
    changeConflict: '这笔账刚被改过，请刷新后再试',
    changesRequired: '没有要保存的改动',
    changesTooMany: `一次最多 ${LIMITS.changes} 项改动`,
    settlementSamePerson: '付款人和收款人不能相同',
    imageTooLarge: '图片过大',
    imageFormat: '图片格式不支持',
    validUntilBeforeFrom: '结束时间必须晚于开始时间',
  },
  en: {
    invalidParams: 'Invalid request',
    internalError: 'Something went wrong on our end. Please try again later',
    apiNotFound: 'Endpoint not found',
    crossSiteRejected: 'Cross-site request rejected',
    unknownMethod: ({ method }) => `Unknown method ${method}`,
    tooManyAttempts: 'Too many attempts. Please try again later',
    unauthorized: 'Not signed in, or your session has expired',
    adminSessionInvalid: 'Your admin session is no longer valid. Please sign in again',
    adminSessionExpired: 'Your admin session has expired. Please sign in again',
    passwordLoginDisabled: 'Password sign-in is not enabled',
    wrongPassword: 'Incorrect password',
    sharedModeNoPassphrase: 'No passcode is needed in shared mode',
    ledgerSessionExpired: 'Your ledger session in this browser has expired. Please enter the passcode',
    passphraseRequired: 'Please enter the ledger passcode',
    passphraseInvalid: 'Invalid or expired passcode',
    passphraseNotYetValid: 'This passcode is not active yet',
    passphraseInUse: 'This passcode is already in use. Please choose another',
    passphraseNotFound: 'Passcode not found',
    ledgerNotFound: 'Ledger not found',
    ledgerExists: ({ name }) => `A ledger named “${name}” already exists`,
    memberNotFound: 'Member not found',
    memberExists: ({ name }) => `A member named “${name}” already exists`,
    memberLimit: `A ledger can have at most ${LIMITS.members} members`,
    memberInUse: 'This member has related records and cannot be removed',
    payerNotFound: 'Payer not found',
    participantNotFound: 'Participant not found',
    expenseNotFound: 'This expense does not exist or has been deleted',
    settlementNotFound: 'This payment does not exist or has been deleted',
    connectionNotFound: 'This connection does not exist or has been disconnected',
    assistantDisabled: 'The AI assistant is not enabled',
    assistantRateLimited: 'The AI assistant is busy. Please try again later',
    assistantUnavailable: 'The AI assistant is temporarily unavailable. Please try again later',
    assistantFailed: 'The AI assistant ran into a problem. Please try again',
    mcpDisabled: 'MCP is not enabled',
    oauthMissingClientId: 'The authorization request is missing client_id',
    oauthUnknownClient: 'Unknown client. Please re-add the connection in your AI app',
    oauthRedirectMismatch: 'The redirect URI does not match the registered client',
    oauthScopeRequired: 'At least read access is required',
    titleRequired: 'Description is required',
    titleTooLong: `Description can be at most ${LIMITS.title} characters`,
    memberNameRequired: 'Name is required',
    memberNameTooLong: `Name can be at most ${LIMITS.memberName} characters`,
    ledgerNameRequired: 'Ledger name is required',
    ledgerNameTooLong: `Ledger name can be at most ${LIMITS.ledgerName} characters`,
    dateFormat: 'Date must be in YYYY-MM-DD format',
    dateInvalid: 'Invalid date',
    amountNotCents: 'Amount must be in cents',
    amountNotPositive: 'Amount must be greater than 0',
    amountTooLarge: 'Amount is too large',
    codeTooShort: `Passcode must be at least ${LIMITS.codeMin} characters`,
    codeTooLong: `Passcode can be at most ${LIMITS.codeMax} characters`,
    codeCharset: 'Passcode can only contain letters and digits',
    participantsRequired: 'Select at least one participant',
    participantsDuplicate: 'Duplicate participants',
    participantsTooMany: `At most ${LIMITS.members} participants`,
    shareNotPositive: 'Each share must be at least 0.01',
    sharesDuplicate: 'Duplicate members in the split',
    sharesSumMismatch: 'Shares must add up to the total',
    categoryInvalid: 'Invalid category',
    idInvalid: 'Invalid record ID',
    idExists: 'This record already exists',
    changeConflict: 'This record was just changed. Refresh and try again',
    changesRequired: 'Nothing to save',
    changesTooMany: `At most ${LIMITS.changes} changes at a time`,
    settlementSamePerson: 'Payer and recipient must be different',
    imageTooLarge: 'Image is too large',
    imageFormat: 'Unsupported image format',
    validUntilBeforeFrom: 'End time must be later than start time',
  },
});

type Catalog = (typeof ERRORS)['zh-CN'];
export type ErrorKey = keyof Catalog;
type ParamsOf<K extends ErrorKey> = Catalog[K] extends (params: infer P) => string ? [params: P] : [];
export type ErrorArgs = { [K in ErrorKey]: [key: K, ...params: ParamsOf<K>] }[ErrorKey];

export type PlainErrorKey = { [K in ErrorKey]: ParamsOf<K> extends [] ? K : never }[ErrorKey];

export const isPlainErrorKey = (key: string): key is PlainErrorKey =>
  Object.hasOwn(ERRORS['zh-CN'], key) && typeof ERRORS['zh-CN'][key as ErrorKey] === 'string';

export function translateError(locale: Locale, ...[key, params]: ErrorArgs | [key: PlainErrorKey]): string {
  const entry: string | ((p: never) => string) = ERRORS[locale][key];
  return typeof entry === 'function' ? entry(params as never) : entry;
}
